/**
 * workspace_readmes.ts — README content generated INTO the workspace (SB-005).
 *
 * Story: SB-005 (Phase 1A, EPIC-CORE-001).
 *
 * These templates are written into the external data workspace (never committed to
 * the repo). They document what is authoritative vs rebuildable and the secure_refs
 * pointer pattern. Kept here so `init_workspace.ts` stays lean. Content is aligned
 * with docs/architecture/privacy_and_security.md.
 */

/** Top-level `README.md` for the data workspace root. */
export const WORKSPACE_README = `# Personal Second Brain — Data Workspace

This directory is your **private data workspace**, created by \`scripts/init_workspace.ts\`
from the \`personal-second-brain\` repository. It deliberately lives **outside** the repo.

## ⚠️ NEVER commit this directory

It holds real personal/private data. It must never be committed to git or shared. The
repo's \`.gitignore\` already blocks workspace paths as defense-in-depth.

## What lives here — authoritative vs rebuildable

| Path | Role | Authority |
|------|------|-----------|
| \`vault/00_Raw/\` | L0 raw source material | **Immutable** — never overwritten or deleted |
| \`vault/…\` | notes (inbox, projects, areas, resources, …) | source content |
| \`events/*.jsonl\` | append-only event log | **Source of truth** — never rewritten |
| \`db/\` | SQLite projections | Rebuildable from \`events/\` + vault |
| \`indexes/\` | retrieval indexes (L4) | Disposable / rebuildable |
| \`attachments/non_sensitive/\` | non-sensitive attachments | source content |
| \`secure_refs/\` | pointers to sensitive material | metadata only (see its README) |
| \`logs/\` | technical/debug logs | Disposable |

## Key invariants

- **\`vault/00_Raw/\` is immutable:** AI never overwrites or deletes raw capture.
- **\`events/\` is the append-only source of truth** — not disposable logs.
- **\`db/\` and \`indexes/\` are rebuildable** from \`events/\` + the vault at any time.
- **Sensitive documents are never stored here** — only pointers in \`secure_refs/\`.

_Generated by init_workspace.ts. Safe to edit — re-running init will not overwrite an
existing README._
`;

/** \`secure_refs/README.md\` — the pointers-only safety note. */
export const SECURE_REFS_README = `# secure_refs/ — Pointers Only

This folder holds **metadata and pointers** to sensitive material kept in secure,
external storage. It must **never** contain raw sensitive documents.

## Rules

- **No raw sensitive content** here (IDs, passports, bank/tax/paystub documents, etc.).
- Store only a **reference**: a frontmatter-only \`<id>.md\` with an opaque \`locator\`
  plus non-sensitive metadata (type, date, source, checksum) needed to find and verify
  the external item.
- The actual secure storage (encrypted volume, keychain, etc.) lives outside this
  workspace.

## Example (frontmatter only — no sensitive content)

\`\`\`yaml
# secure_refs/<id>.md
id: <stable-id>
type: <document-type>
locator: "vault://external/encrypted-volume/ref"   # opaque pointer
date: <YYYY-MM-DD>
\`\`\`

See \`docs/architecture/privacy_and_security.md\` in the repo for the full pattern.
`;

/** Map a planned README's workspace-relative path to its content. */
export function readmeContentFor(rel: string): string | undefined {
  switch (rel) {
    case "README.md":
      return WORKSPACE_README;
    case "secure_refs/README.md":
      return SECURE_REFS_README;
    default:
      return undefined;
  }
}
